services:
  frontend:
    container_name: tripkey-frontend
    depends_on:
      - backend
    networks:
      - tripkey-network

  backend:
    container_name: tripkey-backend
    environment:
      AI_ENGINE_URL: http://tripkey-ai-engine:8000
    depends_on:
      - ai-engine
    networks:
      - tripkey-network

  ai-engine:
    container_name: tripkey-ai-engine
    networks:
      - tripkey-network

networks:
  tripkey-network:
    driver: bridge
