apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripkey-frontend
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripkey-backend
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripkey-ai-engine
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripkey-ai-worker
spec:
  replicas: 1
