apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: tripkey

namespace: tripkey

resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml
  - ai-engine-deployment.yaml
  - ai-engine-service.yaml
  - ai-engine-hpa.yaml
  - ai-worker-deployment.yaml
  - ai-worker-service.yaml
  - ai-worker-hpa.yaml
  - ingress.yaml

images:
  - name: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/tripkey-frontend
    newName: 400524748280.dkr.ecr.ap-northeast-2.amazonaws.com/tripkey-frontend
    newTag: latest
  - name: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/tripkey-backend
    newName: 400524748280.dkr.ecr.ap-northeast-2.amazonaws.com/tripkey-backend
    newTag: latest
  - name: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/tripkey-ai-engine
    newName: 400524748280.dkr.ecr.ap-northeast-2.amazonaws.com/tripkey-ai-engine
    newTag: latest
