apiVersion: v1
kind: ServiceAccount
metadata:
  name: tripkey-ai-worker
  labels:
    app.kubernetes.io/name: tripkey
    app.kubernetes.io/component: ai-worker
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::400524748280:role/TripKeyAiWorkerRole

