from __future__ import annotations

from app.schemas.parse import ParseRequest


def build_core_parse_prompt(req: ParseRequest) -> str:
    accommodation_text = ""
    if req.accommodation_inputs:
        lines = []
        for i, acc in enumerate(req.accommodation_inputs):
            lines.append(
                f"  - Accommodation {i + 1}: "
                f"name={acc.name or 'unknown'}, "
                f"location={acc.location or 'unknown'}, "
                f"check_in={acc.check_in or 'unknown'}, "
                f"check_out={acc.check_out or 'unknown'}"
            )
        accommodation_text = "\n".join(lines)

    departure_text = ""
    if req.departure_flight:
        d = req.departure_flight
        departure_text = (
            f"  - Departure flight: "
            f"{d.departure_airport or 'unknown'} → {d.arrival_airport or 'unknown'}, "
            f"flight={d.flight_number or 'unknown'}, "
            f"datetime={d.datetime or 'unknown'}"
        )

    return_text = ""
    if req.return_flight:
        r = req.return_flight
        return_text = (
            f"  - Return flight: "
            f"{r.departure_airport or 'unknown'} → {r.arrival_airport or 'unknown'}, "
            f"flight={r.flight_number or 'unknown'}, "
            f"datetime={r.datetime or 'unknown'}"
        )

    context_lines = [
        f"- Destinations: {', '.join(req.destinations)}",
        f"- Travel days: {req.travel_days} days",
        f"- Companions: {req.companion_count} people",
    ]
    if accommodation_text:
        context_lines.append(f"- Accommodations:\n{accommodation_text}")
    if departure_text:
        context_lines.append(departure_text)
    if return_text:
        context_lines.append(return_text)

    context_block = "\n".join(context_lines)

    return f"""You are a travel planning AI. Parse the user's travel dump text into structured place cards.

## Trip Context
{context_block}

## Dump Text
{req.dump_text}

## Instructions

### Output Rules
- Return exactly one JSON object. No markdown, no code fences, no explanations.
- cards array must not be empty.
- All enum fields must use exact values defined below.
- Do not generate instance_id.
- Core Parse must not resolve Google Places data. Always set place_id, coordinates, and address to null.
- search_alias is optional, but generate it when the original name is Korean and a local-language or search-friendly alias would improve Google Places matching.

### Card Generation Rules
- Extract every place, activity, food, accommodation, and transport the user mentioned.
- If the user only mentioned a destination with no specific places, generate at least 3 likely place cards with is_ai_generated: true and classification: open_question.
- Accommodation cards must be generated from the structured accommodation inputs above, not inferred from dump_text.
- Flight cards must be generated from the structured flight inputs above, not inferred from dump_text.
- For each accommodation input, create exactly one accommodation card.
- For each flight input provided, create exactly one transport card.

### classification Rules
- confirmed: user clearly intends to visit.
- open_question: user is uncertain or AI-generated recommendation.
- undecided: user will go but specific place is not decided.
- unassigned: AI cannot interpret user intent at all.

### placement_status Rules
- confirmed / open_question → ready_partial
- undecided → needs_input
- unassigned → blocked

### category Rules
- place: 관광지, 명소, 랜드마크
- activity: 체험, 투어, 액티비티
- transport: 교통, 항공편, 이동수단
- accommodation: 숙소, 호텔, 펜션
- food: 식당, 카페, 맛집
- etc: 기타 분류 불가

### Text Field Language Rules
- context_summary, user_context, tips, question_text, options, blocked_reason must be written in Korean.
- name, search_alias, location may use the most natural display language.

### estimated_duration_min Guidelines
- accommodation: null
- transport: null
- place: 60~120
- activity: 60~180
- food: 45~90
- etc: 60

### is_ai_generated Rules
- false: explicitly mentioned by user or from structured inputs
- true: generated by AI as recommendation

### allow_duplicate Rules
- accommodation: always true
- transport: always true
- others: false by default
- Exception: if user explicitly intends to visit multiple of the same type, set true

### question_text / options Rules
- Only use for undecided cards.
- question_text: a short Korean question to ask the user
- options: 2~4 suggested answer options in Korean
- Leave both null for non-undecided cards

### blocked_reason Rules
- Only use for unassigned cards.
- Write a short Korean explanation of why the card could not be interpreted

### search_alias Rules
- Generate a single search-friendly alias only if it is likely to improve Google Places matching.
- Prefer local-language naming for destination countries where local script is commonly used.
- Examples:
  - 도쿄타워 → 東京タワー
  - 오사카성 → 大阪城
- If unnecessary, set null.

## Response Schema
{{
  "context_summary": "string",
  "cards": [
    {{
      "name": "string",
      "category": "place" | "activity" | "transport" | "accommodation" | "food" | "etc",
      "classification": "confirmed" | "open_question" | "undecided" | "unassigned",
      "placement_status": "ready_partial" | "needs_input" | "blocked",
      "is_ai_generated": true | false,
      "allow_duplicate": true | false,
      "estimated_duration_min": number | null,
      "place_id": null,
      "coordinates": null,
      "location": "string | null",
      "address": null,
      "time_constraint": "string | null",
      "question_text": "string | null",
      "options": ["string"] | null,
      "blocked_reason": "string | null",
      "user_context": "string | null",
      "tips": "string | null",
      "tags": ["string"] | null,
      "source": "string | null",
      "search_alias": "string | null",
      "check_in": "string | null",
      "check_out": "string | null",
      "flight_number": "string | null"
    }}
  ],
  "alert_cards": [
    {{
      "id": "string",
      "type": "string",
      "category": "practical" | "insight",
      "scope": "trip",
      "day": null,
      "message": "string",
      "related_instance_ids": null
    }}
  ]
}}
"""
