spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 0
      idle-timeout: 10000
      keepalive-time: 0
      max-lifetime: 30000
      connection-timeout: 10000
      data-source-properties:
        prepareThreshold: 0
        preparedStatementCacheQueries: 0
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
    open-in-view: false
