spring:
  application:
    name: backend
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  default-produces-media-type: application/json

app:
  ai-engine:
    base-url: ${AI_ENGINE_URL:http://tripkey-ai-engine:8000}
